apiVersion: v2
name: devops-genie
description: devops genie ai assistant agent
type: application
version: 0.1.2
appVersion: "0.1.5"
kubeVersion: ">=1.19.0-0"
keywords:
  - devops-genie
  - claude
  - ai
home: https://github.com/devopsgenie-ai/devopsgenie-charts
sources:
  - https://github.com/devopsgenie-ai/devopsgenie-charts
maintainers:
  - name: DevOps Genie
    url: https://github.com/devopsgenie-ai
