{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "devops-genie.fullname" . }}
  labels:
    {{- include "devops-genie.labels" . | nindent 4 }}
{{- end }}
